### ISSUE TITLE
Kendra Index being being forced replaced without any changes to the resource definition

### ISSUE THREAD

**Issue by acbsn** [hashicorp/terraform-provider-awscc#1795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

We have integrated terraform with Gitlab, so we are using the gitlab's latest stable docker image:

```
registry.gitlab.com/gitlab-org/terraform-images/stable:latest
```

Provider:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
}
```

### Affected Resource(s)

* awscc_kendra_index

### Terraform Configuration Files

```
resource "awscc_kendra_index" "example" {
  edition     = "ENTERPRISE_EDITION"
  name        = "example"
  role_arn    = awscc_iam_role.kendra_iam_role.arn
  description = "example"
}
```
### Expected Behavior

Running `terraform plan` without any changes to the kendra index definition should not force replace the resource.

### Actual Behavior

After deploying the kendra index, running plan again always displays:

```
      + server_side_encryption_configuration = (known after apply) # forces replacement

``` 

causing the index to be deleted and recreated.

I tried explicitly adding a null configuration for the kms key, but it did not work.

```
  server_side_encryption_configuration = {
    kms_key_id = null
  }
```

And  I also tried adding a lifecycle policy, but it also did not work,

```
lifecycle {
      ignore_changes = [
        server_side_encryption_configuration
      ]
    }
```

### Steps to Reproduce

```
plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform:  ${TF_ROOT}/plan.json

apply:
  stage: deploy
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual
```

### References

This issue might be related to: https://github.com/hashicorp/terraform-provider-awscc/issues/1562
